/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaExternalLink } from './MediaExternalLink';
import {
    MediaExternalLinkFromJSON,
    MediaExternalLinkFromJSONTyped,
    MediaExternalLinkToJSON,
    MediaExternalLinkToJSONTyped,
} from './MediaExternalLink';

/**
 * 
 * @export
 * @interface ClientConfig
 */
export interface ClientConfig {
    /**
     * 
     * @type {Array<MediaExternalLink>}
     * @memberof ClientConfig
     */
    mediaExternalLinks?: Array<MediaExternalLink>;
}

/**
 * Check if a given object implements the ClientConfig interface.
 */
export function instanceOfClientConfig(value: object): value is ClientConfig {
    return true;
}

export function ClientConfigFromJSON(json: any): ClientConfig {
    return ClientConfigFromJSONTyped(json, false);
}

export function ClientConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaExternalLinks': json['mediaExternalLinks'] == null ? undefined : ((json['mediaExternalLinks'] as Array<any>).map(MediaExternalLinkFromJSON)),
    };
}

export function ClientConfigToJSON(json: any): ClientConfig {
    return ClientConfigToJSONTyped(json, false);
}

export function ClientConfigToJSONTyped(value?: ClientConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mediaExternalLinks': value['mediaExternalLinks'] == null ? undefined : ((value['mediaExternalLinks'] as Array<any>).map(MediaExternalLinkToJSON)),
    };
}

