/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkIcon
 */
export interface LinkIcon {
    /**
     * 
     * @type {string}
     * @memberof LinkIcon
     */
    uri: string;
    /**
     * 
     * @type {string}
     * @memberof LinkIcon
     */
    uriDark?: string;
}

/**
 * Check if a given object implements the LinkIcon interface.
 */
export function instanceOfLinkIcon(value: object): value is LinkIcon {
    if (!('uri' in value) || value['uri'] === undefined) return false;
    return true;
}

export function LinkIconFromJSON(json: any): LinkIcon {
    return LinkIconFromJSONTyped(json, false);
}

export function LinkIconFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkIcon {
    if (json == null) {
        return json;
    }
    return {
        
        'uri': json['uri'],
        'uriDark': json['uriDark'] == null ? undefined : json['uriDark'],
    };
}

export function LinkIconToJSON(json: any): LinkIcon {
    return LinkIconToJSONTyped(json, false);
}

export function LinkIconToJSONTyped(value?: LinkIcon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uri': value['uri'],
        'uriDark': value['uriDark'],
    };
}

