/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkRoutes
 */
export interface LinkRoutes {
    /**
     * 
     * @type {string}
     * @memberof LinkRoutes
     */
    episode?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkRoutes
     */
    movie?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkRoutes
     */
    season?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkRoutes
     */
    show?: string;
}

/**
 * Check if a given object implements the LinkRoutes interface.
 */
export function instanceOfLinkRoutes(value: object): value is LinkRoutes {
    return true;
}

export function LinkRoutesFromJSON(json: any): LinkRoutes {
    return LinkRoutesFromJSONTyped(json, false);
}

export function LinkRoutesFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkRoutes {
    if (json == null) {
        return json;
    }
    return {
        
        'episode': json['episode'] == null ? undefined : json['episode'],
        'movie': json['movie'] == null ? undefined : json['movie'],
        'season': json['season'] == null ? undefined : json['season'],
        'show': json['show'] == null ? undefined : json['show'],
    };
}

export function LinkRoutesToJSON(json: any): LinkRoutes {
    return LinkRoutesToJSONTyped(json, false);
}

export function LinkRoutesToJSONTyped(value?: LinkRoutes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'episode': value['episode'],
        'movie': value['movie'],
        'season': value['season'],
        'show': value['show'],
    };
}

