/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieCrew
 */
export interface MovieCrew {
    /**
     * 
     * @type {string}
     * @memberof MovieCrew
     */
    creditId?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieCrew
     */
    department?: string;
    /**
     * 
     * @type {number}
     * @memberof MovieCrew
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MovieCrew
     */
    job?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieCrew
     */
    knownForDepartment?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieCrew
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof MovieCrew
     */
    popularity: number;
    /**
     * 
     * @type {string}
     * @memberof MovieCrew
     */
    profilePath?: string;
}

/**
 * Check if a given object implements the MovieCrew interface.
 */
export function instanceOfMovieCrew(value: object): value is MovieCrew {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('popularity' in value) || value['popularity'] === undefined) return false;
    return true;
}

export function MovieCrewFromJSON(json: any): MovieCrew {
    return MovieCrewFromJSONTyped(json, false);
}

export function MovieCrewFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieCrew {
    if (json == null) {
        return json;
    }
    return {
        
        'creditId': json['creditId'] == null ? undefined : json['creditId'],
        'department': json['department'] == null ? undefined : json['department'],
        'id': json['id'],
        'job': json['job'] == null ? undefined : json['job'],
        'knownForDepartment': json['knownForDepartment'] == null ? undefined : json['knownForDepartment'],
        'name': json['name'] == null ? undefined : json['name'],
        'popularity': json['popularity'],
        'profilePath': json['profilePath'] == null ? undefined : json['profilePath'],
    };
}

export function MovieCrewToJSON(json: any): MovieCrew {
    return MovieCrewToJSONTyped(json, false);
}

export function MovieCrewToJSONTyped(value?: MovieCrew | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creditId': value['creditId'],
        'department': value['department'],
        'id': value['id'],
        'job': value['job'],
        'knownForDepartment': value['knownForDepartment'],
        'name': value['name'],
        'popularity': value['popularity'],
        'profilePath': value['profilePath'],
    };
}

