/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisteringUser
 */
export interface RegisteringUser {
    /**
     * 
     * @type {string}
     * @memberof RegisteringUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteringUser
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteringUser
     */
    inviteCode?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteringUser
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisteringUser
     */
    password: string;
}

/**
 * Check if a given object implements the RegisteringUser interface.
 */
export function instanceOfRegisteringUser(value: object): value is RegisteringUser {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegisteringUserFromJSON(json: any): RegisteringUser {
    return RegisteringUserFromJSONTyped(json, false);
}

export function RegisteringUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisteringUser {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'firstName': json['firstName'],
        'inviteCode': json['inviteCode'] == null ? undefined : json['inviteCode'],
        'lastName': json['lastName'],
        'password': json['password'],
    };
}

export function RegisteringUserToJSON(json: any): RegisteringUser {
    return RegisteringUserToJSONTyped(json, false);
}

export function RegisteringUserToJSONTyped(value?: RegisteringUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'firstName': value['firstName'],
        'inviteCode': value['inviteCode'],
        'lastName': value['lastName'],
        'password': value['password'],
    };
}

