version: "3.5"

name: "framerate"
services:
    framerate:
        image: app:latest
        build: .
        container_name: framerate
        volumes:
            - ..:/workspace
            - ~/.npmrc:/home/node/.npmrc
            - ~/.bashrc:/home/node/.bashrc
            - ~/.expo:/home/node/.expo
        network_mode: "host"
        env_file: .env
        command: sleep infinity
