version: "3.5"

name: "movietvapp"
services:
    movietvapp:
        image: app:latest
        build: .
        container_name: movietvapp
        volumes:
            - ..:/workspace
            - ~/.npmrc:/home/node/.npmrc
        network_mode: "host"
        env_file: .env
        command: sleep infinity
