/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Movie,
} from '../models/index';
import {
    MovieFromJSON,
    MovieToJSON,
} from '../models/index';

export interface MovieApiDetailsRequest {
    movieId: number;
}

export interface MovieApiSearchRequest {
    query: string;
}

/**
 * MovieApi - interface
 * 
 * @export
 * @interface MovieApiInterface
 */
export interface MovieApiInterface {
    /**
     * 
     * @param {number} movieId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MovieApiInterface
     */
    detailsRaw(requestParameters: MovieApiDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Movie>>;

    /**
     */
    details(requestParameters: MovieApiDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Movie>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MovieApiInterface
     */
    popularRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Movie>>>;

    /**
     */
    popular(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Movie>>;

    /**
     * 
     * @param {string} query 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MovieApiInterface
     */
    searchRaw(requestParameters: MovieApiSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Movie>>>;

    /**
     */
    search(requestParameters: MovieApiSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Movie>>;

}

/**
 * 
 */
export class MovieApi extends runtime.BaseAPI implements MovieApiInterface {

    /**
     */
    async detailsRaw(requestParameters: MovieApiDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Movie>> {
        if (requestParameters['movieId'] == null) {
            throw new runtime.RequiredError(
                'movieId',
                'Required parameter "movieId" was null or undefined when calling details().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/movies/{movie_id}/details`.replace(`{${"movie_id"}}`, encodeURIComponent(String(requestParameters['movieId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MovieFromJSON(jsonValue));
    }

    /**
     */
    async details(requestParameters: MovieApiDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Movie> {
        const response = await this.detailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async popularRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Movie>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/movies/popular`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MovieFromJSON));
    }

    /**
     */
    async popular(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Movie>> {
        const response = await this.popularRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async searchRaw(requestParameters: MovieApiSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Movie>>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/movies/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MovieFromJSON));
    }

    /**
     */
    async search(requestParameters: MovieApiSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Movie>> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
