/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteResponse,
  NewShowCollection,
  SaveShowCollectionEntryRequest,
  ShowCollection,
  ShowEntry,
  UpdatedCollection,
} from '../models/index';
import {
    DeleteResponseFromJSON,
    DeleteResponseToJSON,
    NewShowCollectionFromJSON,
    NewShowCollectionToJSON,
    SaveShowCollectionEntryRequestFromJSON,
    SaveShowCollectionEntryRequestToJSON,
    ShowCollectionFromJSON,
    ShowCollectionToJSON,
    ShowEntryFromJSON,
    ShowEntryToJSON,
    UpdatedCollectionFromJSON,
    UpdatedCollectionToJSON,
} from '../models/index';

export interface ShowCollectionApiDeleteRequest {
    collectionId: string;
}

export interface ShowCollectionApiCreateRequest {
    newShowCollection: NewShowCollection;
}

export interface ShowCollectionApiCreateEntryRequest {
    collectionId: string;
    saveShowCollectionEntryRequest: SaveShowCollectionEntryRequest;
}

export interface ShowCollectionApiDeleteEntryRequest {
    collectionId: string;
    showId: number;
}

export interface ShowCollectionApiFindRequest {
    collectionId: string;
}

export interface ShowCollectionApiFindByShowRequest {
    showId: number;
}

export interface ShowCollectionApiUpdateRequest {
    collectionId: string;
    updatedCollection: UpdatedCollection;
}

/**
 * ShowCollectionApi - interface
 * 
 * @export
 * @interface ShowCollectionApiInterface
 */
export interface ShowCollectionApiInterface {
    /**
     * 
     * @param {string} collectionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowCollectionApiInterface
     */
    _deleteRaw(requestParameters: ShowCollectionApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteResponse>>;

    /**
     */
    _delete(requestParameters: ShowCollectionApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteResponse>;

    /**
     * 
     * @param {NewShowCollection} newShowCollection 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowCollectionApiInterface
     */
    createRaw(requestParameters: ShowCollectionApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShowCollection>>;

    /**
     */
    create(requestParameters: ShowCollectionApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShowCollection>;

    /**
     * 
     * @param {string} collectionId 
     * @param {SaveShowCollectionEntryRequest} saveShowCollectionEntryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowCollectionApiInterface
     */
    createEntryRaw(requestParameters: ShowCollectionApiCreateEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShowEntry>>;

    /**
     */
    createEntry(requestParameters: ShowCollectionApiCreateEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShowEntry>;

    /**
     * 
     * @param {string} collectionId 
     * @param {number} showId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowCollectionApiInterface
     */
    deleteEntryRaw(requestParameters: ShowCollectionApiDeleteEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteResponse>>;

    /**
     */
    deleteEntry(requestParameters: ShowCollectionApiDeleteEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteResponse>;

    /**
     * 
     * @param {string} collectionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowCollectionApiInterface
     */
    findRaw(requestParameters: ShowCollectionApiFindRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShowCollection>>;

    /**
     */
    find(requestParameters: ShowCollectionApiFindRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShowCollection>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowCollectionApiInterface
     */
    findAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ShowCollection>>>;

    /**
     */
    findAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ShowCollection>>;

    /**
     * 
     * @param {number} showId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowCollectionApiInterface
     */
    findByShowRaw(requestParameters: ShowCollectionApiFindByShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     */
    findByShow(requestParameters: ShowCollectionApiFindByShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

    /**
     * 
     * @param {string} collectionId 
     * @param {UpdatedCollection} updatedCollection 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShowCollectionApiInterface
     */
    updateRaw(requestParameters: ShowCollectionApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShowCollection>>;

    /**
     */
    update(requestParameters: ShowCollectionApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShowCollection>;

}

/**
 * 
 */
export class ShowCollectionApi extends runtime.BaseAPI implements ShowCollectionApiInterface {

    /**
     */
    async _deleteRaw(requestParameters: ShowCollectionApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteResponse>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling _delete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/shows/collections/{collection_id}`.replace(`{${"collection_id"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteResponseFromJSON(jsonValue));
    }

    /**
     */
    async _delete(requestParameters: ShowCollectionApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteResponse> {
        const response = await this._deleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createRaw(requestParameters: ShowCollectionApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShowCollection>> {
        if (requestParameters['newShowCollection'] == null) {
            throw new runtime.RequiredError(
                'newShowCollection',
                'Required parameter "newShowCollection" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/shows/collections`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewShowCollectionToJSON(requestParameters['newShowCollection']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShowCollectionFromJSON(jsonValue));
    }

    /**
     */
    async create(requestParameters: ShowCollectionApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShowCollection> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createEntryRaw(requestParameters: ShowCollectionApiCreateEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShowEntry>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling createEntry().'
            );
        }

        if (requestParameters['saveShowCollectionEntryRequest'] == null) {
            throw new runtime.RequiredError(
                'saveShowCollectionEntryRequest',
                'Required parameter "saveShowCollectionEntryRequest" was null or undefined when calling createEntry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/shows/collections/{collection_id}`.replace(`{${"collection_id"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveShowCollectionEntryRequestToJSON(requestParameters['saveShowCollectionEntryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShowEntryFromJSON(jsonValue));
    }

    /**
     */
    async createEntry(requestParameters: ShowCollectionApiCreateEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShowEntry> {
        const response = await this.createEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteEntryRaw(requestParameters: ShowCollectionApiDeleteEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteResponse>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling deleteEntry().'
            );
        }

        if (requestParameters['showId'] == null) {
            throw new runtime.RequiredError(
                'showId',
                'Required parameter "showId" was null or undefined when calling deleteEntry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/shows/collections/{collection_id}/{show_id}`.replace(`{${"collection_id"}}`, encodeURIComponent(String(requestParameters['collectionId']))).replace(`{${"show_id"}}`, encodeURIComponent(String(requestParameters['showId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteResponseFromJSON(jsonValue));
    }

    /**
     */
    async deleteEntry(requestParameters: ShowCollectionApiDeleteEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteResponse> {
        const response = await this.deleteEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async findRaw(requestParameters: ShowCollectionApiFindRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShowCollection>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling find().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/shows/collections/{collection_id}`.replace(`{${"collection_id"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShowCollectionFromJSON(jsonValue));
    }

    /**
     */
    async find(requestParameters: ShowCollectionApiFindRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShowCollection> {
        const response = await this.findRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async findAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ShowCollection>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/shows/collections`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ShowCollectionFromJSON));
    }

    /**
     */
    async findAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ShowCollection>> {
        const response = await this.findAllRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async findByShowRaw(requestParameters: ShowCollectionApiFindByShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['showId'] == null) {
            throw new runtime.RequiredError(
                'showId',
                'Required parameter "showId" was null or undefined when calling findByShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/shows/collections/show/{show_id}`.replace(`{${"show_id"}}`, encodeURIComponent(String(requestParameters['showId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async findByShow(requestParameters: ShowCollectionApiFindByShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.findByShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateRaw(requestParameters: ShowCollectionApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShowCollection>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling update().'
            );
        }

        if (requestParameters['updatedCollection'] == null) {
            throw new runtime.RequiredError(
                'updatedCollection',
                'Required parameter "updatedCollection" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/shows/collections/{collection_id}`.replace(`{${"collection_id"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatedCollectionToJSON(requestParameters['updatedCollection']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShowCollectionFromJSON(jsonValue));
    }

    /**
     */
    async update(requestParameters: ShowCollectionApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShowCollection> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
