/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    companyId: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    createdBy: string;
    /**
     * 
     * @type {Date}
     * @memberof Company
     */
    dateCreated: Date;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    userId?: string;
}

/**
 * Check if a given object implements the Company interface.
 */
export function instanceOfCompany(value: object): value is Company {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('dateCreated' in value) || value['dateCreated'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function CompanyFromJSON(json: any): Company {
    return CompanyFromJSONTyped(json, false);
}

export function CompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Company {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['companyId'],
        'createdBy': json['createdBy'],
        'dateCreated': (new Date(json['dateCreated'])),
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function CompanyToJSON(json: any): Company {
    return CompanyToJSONTyped(json, false);
}

export function CompanyToJSONTyped(value?: Company | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyId': value['companyId'],
        'createdBy': value['createdBy'],
        'dateCreated': ((value['dateCreated']).toISOString()),
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'userId': value['userId'],
    };
}

