/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Cast } from './cast';
import {
    CastFromJSON,
    CastFromJSONTyped,
    CastToJSON,
    CastToJSONTyped,
} from './cast';
import type { Crew } from './crew';
import {
    CrewFromJSON,
    CrewFromJSONTyped,
    CrewToJSON,
    CrewToJSONTyped,
} from './crew';

/**
 * 
 * @export
 * @interface Credits
 */
export interface Credits {
    /**
     * 
     * @type {Array<Cast>}
     * @memberof Credits
     */
    cast: Array<Cast>;
    /**
     * 
     * @type {Array<Crew>}
     * @memberof Credits
     */
    crew: Array<Crew>;
}

/**
 * Check if a given object implements the Credits interface.
 */
export function instanceOfCredits(value: object): value is Credits {
    if (!('cast' in value) || value['cast'] === undefined) return false;
    if (!('crew' in value) || value['crew'] === undefined) return false;
    return true;
}

export function CreditsFromJSON(json: any): Credits {
    return CreditsFromJSONTyped(json, false);
}

export function CreditsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Credits {
    if (json == null) {
        return json;
    }
    return {
        
        'cast': ((json['cast'] as Array<any>).map(CastFromJSON)),
        'crew': ((json['crew'] as Array<any>).map(CrewFromJSON)),
    };
}

export function CreditsToJSON(json: any): Credits {
    return CreditsToJSONTyped(json, false);
}

export function CreditsToJSONTyped(value?: Credits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cast': ((value['cast'] as Array<any>).map(CastToJSON)),
        'crew': ((value['crew'] as Array<any>).map(CrewToJSON)),
    };
}

