/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Crew
 */
export interface Crew {
    /**
     * 
     * @type {string}
     * @memberof Crew
     */
    creditId?: string;
    /**
     * 
     * @type {string}
     * @memberof Crew
     */
    department?: string;
    /**
     * 
     * @type {number}
     * @memberof Crew
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Crew
     */
    job?: string;
    /**
     * 
     * @type {string}
     * @memberof Crew
     */
    knownForDepartment?: string;
    /**
     * 
     * @type {string}
     * @memberof Crew
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Crew
     */
    popularity: number;
    /**
     * 
     * @type {string}
     * @memberof Crew
     */
    profilePath?: string;
}

/**
 * Check if a given object implements the Crew interface.
 */
export function instanceOfCrew(value: object): value is Crew {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('popularity' in value) || value['popularity'] === undefined) return false;
    return true;
}

export function CrewFromJSON(json: any): Crew {
    return CrewFromJSONTyped(json, false);
}

export function CrewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Crew {
    if (json == null) {
        return json;
    }
    return {
        
        'creditId': json['creditId'] == null ? undefined : json['creditId'],
        'department': json['department'] == null ? undefined : json['department'],
        'id': json['id'],
        'job': json['job'] == null ? undefined : json['job'],
        'knownForDepartment': json['knownForDepartment'] == null ? undefined : json['knownForDepartment'],
        'name': json['name'] == null ? undefined : json['name'],
        'popularity': json['popularity'],
        'profilePath': json['profilePath'] == null ? undefined : json['profilePath'],
    };
}

export function CrewToJSON(json: any): Crew {
    return CrewToJSONTyped(json, false);
}

export function CrewToJSONTyped(value?: Crew | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creditId': value['creditId'],
        'department': value['department'],
        'id': value['id'],
        'job': value['job'],
        'knownForDepartment': value['knownForDepartment'],
        'name': value['name'],
        'popularity': value['popularity'],
        'profilePath': value['profilePath'],
    };
}

