/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteDetails
 */
export interface InviteDetails {
    /**
     * 
     * @type {string}
     * @memberof InviteDetails
     */
    email: string;
}

/**
 * Check if a given object implements the InviteDetails interface.
 */
export function instanceOfInviteDetails(value: object): value is InviteDetails {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function InviteDetailsFromJSON(json: any): InviteDetails {
    return InviteDetailsFromJSONTyped(json, false);
}

export function InviteDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function InviteDetailsToJSON(json: any): InviteDetails {
    return InviteDetailsToJSONTyped(json, false);
}

export function InviteDetailsToJSONTyped(value?: InviteDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

