/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieEntry
 */
export interface MovieEntry {
    /**
     * 
     * @type {string}
     * @memberof MovieEntry
     */
    collectionId: string;
    /**
     * 
     * @type {string}
     * @memberof MovieEntry
     */
    imdbId?: string;
    /**
     * 
     * @type {number}
     * @memberof MovieEntry
     */
    movieId: number;
    /**
     * 
     * @type {string}
     * @memberof MovieEntry
     */
    posterPath?: string;
    /**
     * 
     * @type {Date}
     * @memberof MovieEntry
     */
    releaseDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof MovieEntry
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieEntry
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof MovieEntry
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof MovieEntry
     */
    userId: string;
}

/**
 * Check if a given object implements the MovieEntry interface.
 */
export function instanceOfMovieEntry(value: object): value is MovieEntry {
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('movieId' in value) || value['movieId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function MovieEntryFromJSON(json: any): MovieEntry {
    return MovieEntryFromJSONTyped(json, false);
}

export function MovieEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionId': json['collectionId'],
        'imdbId': json['imdbId'] == null ? undefined : json['imdbId'],
        'movieId': json['movieId'],
        'posterPath': json['posterPath'] == null ? undefined : json['posterPath'],
        'releaseDate': json['releaseDate'] == null ? undefined : (new Date(json['releaseDate'])),
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'],
        'updatedAt': (new Date(json['updatedAt'])),
        'userId': json['userId'],
    };
}

export function MovieEntryToJSON(json: any): MovieEntry {
    return MovieEntryToJSONTyped(json, false);
}

export function MovieEntryToJSONTyped(value?: MovieEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collectionId': value['collectionId'],
        'imdbId': value['imdbId'],
        'movieId': value['movieId'],
        'posterPath': value['posterPath'],
        'releaseDate': value['releaseDate'] == null ? undefined : ((value['releaseDate']).toISOString().substring(0,10)),
        'status': value['status'],
        'title': value['title'],
        'updatedAt': ((value['updatedAt']).toISOString().substring(0,10)),
        'userId': value['userId'],
    };
}

