/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MovieWatchlistEntry } from './MovieWatchlistEntry';
import {
    MovieWatchlistEntryFromJSON,
    MovieWatchlistEntryFromJSONTyped,
    MovieWatchlistEntryToJSON,
    MovieWatchlistEntryToJSONTyped,
} from './MovieWatchlistEntry';

/**
 * 
 * @export
 * @interface MovieWatchlist
 */
export interface MovieWatchlist {
    /**
     * 
     * @type {Array<MovieWatchlistEntry>}
     * @memberof MovieWatchlist
     */
    entries?: Array<MovieWatchlistEntry>;
    /**
     * 
     * @type {string}
     * @memberof MovieWatchlist
     */
    name: string;
}

/**
 * Check if a given object implements the MovieWatchlist interface.
 */
export function instanceOfMovieWatchlist(value: object): value is MovieWatchlist {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MovieWatchlistFromJSON(json: any): MovieWatchlist {
    return MovieWatchlistFromJSONTyped(json, false);
}

export function MovieWatchlistFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieWatchlist {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': json['entries'] == null ? undefined : ((json['entries'] as Array<any>).map(MovieWatchlistEntryFromJSON)),
        'name': json['name'],
    };
}

export function MovieWatchlistToJSON(json: any): MovieWatchlist {
    return MovieWatchlistToJSONTyped(json, false);
}

export function MovieWatchlistToJSONTyped(value?: MovieWatchlist | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(MovieWatchlistEntryToJSON)),
        'name': value['name'],
    };
}

