/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieCast
 */
export interface MovieCast {
    /**
     * 
     * @type {number}
     * @memberof MovieCast
     */
    castId: number;
    /**
     * 
     * @type {string}
     * @memberof MovieCast
     */
    character?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieCast
     */
    creditId?: string;
    /**
     * 
     * @type {number}
     * @memberof MovieCast
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MovieCast
     */
    knownForDepartment?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieCast
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof MovieCast
     */
    popularity: number;
    /**
     * 
     * @type {string}
     * @memberof MovieCast
     */
    profilePath?: string;
}

/**
 * Check if a given object implements the MovieCast interface.
 */
export function instanceOfMovieCast(value: object): value is MovieCast {
    if (!('castId' in value) || value['castId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('popularity' in value) || value['popularity'] === undefined) return false;
    return true;
}

export function MovieCastFromJSON(json: any): MovieCast {
    return MovieCastFromJSONTyped(json, false);
}

export function MovieCastFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieCast {
    if (json == null) {
        return json;
    }
    return {
        
        'castId': json['castId'],
        'character': json['character'] == null ? undefined : json['character'],
        'creditId': json['creditId'] == null ? undefined : json['creditId'],
        'id': json['id'],
        'knownForDepartment': json['knownForDepartment'] == null ? undefined : json['knownForDepartment'],
        'name': json['name'] == null ? undefined : json['name'],
        'popularity': json['popularity'],
        'profilePath': json['profilePath'] == null ? undefined : json['profilePath'],
    };
}

export function MovieCastToJSON(json: any): MovieCast {
    return MovieCastToJSONTyped(json, false);
}

export function MovieCastToJSONTyped(value?: MovieCast | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'castId': value['castId'],
        'character': value['character'],
        'creditId': value['creditId'],
        'id': value['id'],
        'knownForDepartment': value['knownForDepartment'],
        'name': value['name'],
        'popularity': value['popularity'],
        'profilePath': value['profilePath'],
    };
}

