/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewMovieCollection
 */
export interface NewMovieCollection {
    /**
     * 
     * @type {string}
     * @memberof NewMovieCollection
     */
    name: string;
}

/**
 * Check if a given object implements the NewMovieCollection interface.
 */
export function instanceOfNewMovieCollection(value: object): value is NewMovieCollection {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NewMovieCollectionFromJSON(json: any): NewMovieCollection {
    return NewMovieCollectionFromJSONTyped(json, false);
}

export function NewMovieCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewMovieCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function NewMovieCollectionToJSON(json: any): NewMovieCollection {
    return NewMovieCollectionToJSONTyped(json, false);
}

export function NewMovieCollectionToJSONTyped(value?: NewMovieCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

