/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewShowCollection
 */
export interface NewShowCollection {
    /**
     * 
     * @type {string}
     * @memberof NewShowCollection
     */
    name: string;
}

/**
 * Check if a given object implements the NewShowCollection interface.
 */
export function instanceOfNewShowCollection(value: object): value is NewShowCollection {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NewShowCollectionFromJSON(json: any): NewShowCollection {
    return NewShowCollectionFromJSONTyped(json, false);
}

export function NewShowCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewShowCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function NewShowCollectionToJSON(json: any): NewShowCollection {
    return NewShowCollectionToJSONTyped(json, false);
}

export function NewShowCollectionToJSONTyped(value?: NewShowCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

