/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewUser
 */
export interface NewUser {
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    avatarUri?: string;
    /**
     * 
     * @type {any}
     * @memberof NewUser
     */
    configuration?: any | null;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    firstName: string;
    /**
     * 
     * @type {boolean}
     * @memberof NewUser
     */
    isAdmin?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    password: string;
}

/**
 * Check if a given object implements the NewUser interface.
 */
export function instanceOfNewUser(value: object): value is NewUser {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function NewUserFromJSON(json: any): NewUser {
    return NewUserFromJSONTyped(json, false);
}

export function NewUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewUser {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarUri': json['avatarUri'] == null ? undefined : json['avatarUri'],
        'configuration': json['configuration'] == null ? undefined : json['configuration'],
        'email': json['email'],
        'firstName': json['firstName'],
        'isAdmin': json['isAdmin'] == null ? undefined : json['isAdmin'],
        'lastName': json['lastName'],
        'password': json['password'],
    };
}

export function NewUserToJSON(json: any): NewUser {
    return NewUserToJSONTyped(json, false);
}

export function NewUserToJSONTyped(value?: NewUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatarUri': value['avatarUri'],
        'configuration': value['configuration'],
        'email': value['email'],
        'firstName': value['firstName'],
        'isAdmin': value['isAdmin'],
        'lastName': value['lastName'],
        'password': value['password'],
    };
}

