/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewCompanyDetails
 */
export interface ReviewCompanyDetails {
    /**
     * 
     * @type {string}
     * @memberof ReviewCompanyDetails
     */
    companyId: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewCompanyDetails
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewCompanyDetails
     */
    lastName: string;
}

/**
 * Check if a given object implements the ReviewCompanyDetails interface.
 */
export function instanceOfReviewCompanyDetails(value: object): value is ReviewCompanyDetails {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function ReviewCompanyDetailsFromJSON(json: any): ReviewCompanyDetails {
    return ReviewCompanyDetailsFromJSONTyped(json, false);
}

export function ReviewCompanyDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewCompanyDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['companyId'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function ReviewCompanyDetailsToJSON(json: any): ReviewCompanyDetails {
    return ReviewCompanyDetailsToJSONTyped(json, false);
}

export function ReviewCompanyDetailsToJSONTyped(value?: ReviewCompanyDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyId': value['companyId'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

