/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewCompanySummary
 */
export interface ReviewCompanySummary {
    /**
     * 
     * @type {string}
     * @memberof ReviewCompanySummary
     */
    companyId: string;
}

/**
 * Check if a given object implements the ReviewCompanySummary interface.
 */
export function instanceOfReviewCompanySummary(value: object): value is ReviewCompanySummary {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    return true;
}

export function ReviewCompanySummaryFromJSON(json: any): ReviewCompanySummary {
    return ReviewCompanySummaryFromJSONTyped(json, false);
}

export function ReviewCompanySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewCompanySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['companyId'],
    };
}

export function ReviewCompanySummaryToJSON(json: any): ReviewCompanySummary {
    return ReviewCompanySummaryToJSONTyped(json, false);
}

export function ReviewCompanySummaryToJSONTyped(value?: ReviewCompanySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'companyId': value['companyId'],
    };
}

