/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveMovieWatchlistEntryRequest
 */
export interface SaveMovieWatchlistEntryRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveMovieWatchlistEntryRequest
     */
    movieId: number;
}

/**
 * Check if a given object implements the SaveMovieWatchlistEntryRequest interface.
 */
export function instanceOfSaveMovieWatchlistEntryRequest(value: object): value is SaveMovieWatchlistEntryRequest {
    if (!('movieId' in value) || value['movieId'] === undefined) return false;
    return true;
}

export function SaveMovieWatchlistEntryRequestFromJSON(json: any): SaveMovieWatchlistEntryRequest {
    return SaveMovieWatchlistEntryRequestFromJSONTyped(json, false);
}

export function SaveMovieWatchlistEntryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveMovieWatchlistEntryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'movieId': json['movieId'],
    };
}

export function SaveMovieWatchlistEntryRequestToJSON(json: any): SaveMovieWatchlistEntryRequest {
    return SaveMovieWatchlistEntryRequestToJSONTyped(json, false);
}

export function SaveMovieWatchlistEntryRequestToJSONTyped(value?: SaveMovieWatchlistEntryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'movieId': value['movieId'],
    };
}

