/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveShowCollectionEntryRequest
 */
export interface SaveShowCollectionEntryRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveShowCollectionEntryRequest
     */
    showId: number;
}

/**
 * Check if a given object implements the SaveShowCollectionEntryRequest interface.
 */
export function instanceOfSaveShowCollectionEntryRequest(value: object): value is SaveShowCollectionEntryRequest {
    if (!('showId' in value) || value['showId'] === undefined) return false;
    return true;
}

export function SaveShowCollectionEntryRequestFromJSON(json: any): SaveShowCollectionEntryRequest {
    return SaveShowCollectionEntryRequestFromJSONTyped(json, false);
}

export function SaveShowCollectionEntryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveShowCollectionEntryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'showId': json['showId'],
    };
}

export function SaveShowCollectionEntryRequestToJSON(json: any): SaveShowCollectionEntryRequest {
    return SaveShowCollectionEntryRequestToJSONTyped(json, false);
}

export function SaveShowCollectionEntryRequestToJSONTyped(value?: SaveShowCollectionEntryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'showId': value['showId'],
    };
}

