/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveShowWatchlistEntryRequest
 */
export interface SaveShowWatchlistEntryRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveShowWatchlistEntryRequest
     */
    showId: number;
}

/**
 * Check if a given object implements the SaveShowWatchlistEntryRequest interface.
 */
export function instanceOfSaveShowWatchlistEntryRequest(value: object): value is SaveShowWatchlistEntryRequest {
    if (!('showId' in value) || value['showId'] === undefined) return false;
    return true;
}

export function SaveShowWatchlistEntryRequestFromJSON(json: any): SaveShowWatchlistEntryRequest {
    return SaveShowWatchlistEntryRequestFromJSONTyped(json, false);
}

export function SaveShowWatchlistEntryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveShowWatchlistEntryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'showId': json['showId'],
    };
}

export function SaveShowWatchlistEntryRequestToJSON(json: any): SaveShowWatchlistEntryRequest {
    return SaveShowWatchlistEntryRequestToJSONTyped(json, false);
}

export function SaveShowWatchlistEntryRequestToJSONTyped(value?: SaveShowWatchlistEntryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'showId': value['showId'],
    };
}

