/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewCompanySummary } from './ReviewCompanySummary';
import {
    ReviewCompanySummaryFromJSON,
    ReviewCompanySummaryFromJSONTyped,
    ReviewCompanySummaryToJSON,
    ReviewCompanySummaryToJSONTyped,
} from './ReviewCompanySummary';

/**
 * 
 * @export
 * @interface SaveShowReviewRequest
 */
export interface SaveShowReviewRequest {
    /**
     * 
     * @type {Array<ReviewCompanySummary>}
     * @memberof SaveShowReviewRequest
     */
    company?: Array<ReviewCompanySummary>;
    /**
     * 
     * @type {Date}
     * @memberof SaveShowReviewRequest
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof SaveShowReviewRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof SaveShowReviewRequest
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof SaveShowReviewRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveShowReviewRequest
     */
    venue?: string;
}

/**
 * Check if a given object implements the SaveShowReviewRequest interface.
 */
export function instanceOfSaveShowReviewRequest(value: object): value is SaveShowReviewRequest {
    return true;
}

export function SaveShowReviewRequestFromJSON(json: any): SaveShowReviewRequest {
    return SaveShowReviewRequestFromJSONTyped(json, false);
}

export function SaveShowReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveShowReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'company': json['company'] == null ? undefined : ((json['company'] as Array<any>).map(ReviewCompanySummaryFromJSON)),
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'description': json['description'] == null ? undefined : json['description'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'title': json['title'] == null ? undefined : json['title'],
        'venue': json['venue'] == null ? undefined : json['venue'],
    };
}

export function SaveShowReviewRequestToJSON(json: any): SaveShowReviewRequest {
    return SaveShowReviewRequestToJSONTyped(json, false);
}

export function SaveShowReviewRequestToJSONTyped(value?: SaveShowReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'] == null ? undefined : ((value['company'] as Array<any>).map(ReviewCompanySummaryToJSON)),
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'description': value['description'],
        'rating': value['rating'],
        'title': value['title'],
        'venue': value['venue'],
    };
}

