/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveMovieCollectionEntryRequest
 */
export interface SaveMovieCollectionEntryRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveMovieCollectionEntryRequest
     */
    movieId: number;
}

/**
 * Check if a given object implements the SaveMovieCollectionEntryRequest interface.
 */
export function instanceOfSaveMovieCollectionEntryRequest(value: object): value is SaveMovieCollectionEntryRequest {
    if (!('movieId' in value) || value['movieId'] === undefined) return false;
    return true;
}

export function SaveMovieCollectionEntryRequestFromJSON(json: any): SaveMovieCollectionEntryRequest {
    return SaveMovieCollectionEntryRequestFromJSONTyped(json, false);
}

export function SaveMovieCollectionEntryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveMovieCollectionEntryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'movieId': json['movieId'],
    };
}

export function SaveMovieCollectionEntryRequestToJSON(json: any): SaveMovieCollectionEntryRequest {
    return SaveMovieCollectionEntryRequestToJSONTyped(json, false);
}

export function SaveMovieCollectionEntryRequestToJSONTyped(value?: SaveMovieCollectionEntryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'movieId': value['movieId'],
    };
}

