/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveCompany
 */
export interface SaveCompany {
    /**
     * 
     * @type {string}
     * @memberof SaveCompany
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof SaveCompany
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof SaveCompany
     */
    userId?: string;
}

/**
 * Check if a given object implements the SaveCompany interface.
 */
export function instanceOfSaveCompany(value: object): value is SaveCompany {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function SaveCompanyFromJSON(json: any): SaveCompany {
    return SaveCompanyFromJSONTyped(json, false);
}

export function SaveCompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveCompany {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function SaveCompanyToJSON(json: any): SaveCompany {
    return SaveCompanyToJSONTyped(json, false);
}

export function SaveCompanyToJSONTyped(value?: SaveCompany | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'userId': value['userId'],
    };
}

