/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewCompanyDetails } from './ReviewCompanyDetails';
import {
    ReviewCompanyDetailsFromJSON,
    ReviewCompanyDetailsFromJSONTyped,
    ReviewCompanyDetailsToJSON,
    ReviewCompanyDetailsToJSONTyped,
} from './ReviewCompanyDetails';
import type { Season } from './Season';
import {
    SeasonFromJSON,
    SeasonFromJSONTyped,
    SeasonToJSON,
    SeasonToJSONTyped,
} from './Season';

/**
 * 
 * @export
 * @interface SeasonReviewResponse
 */
export interface SeasonReviewResponse {
    /**
     * 
     * @type {Array<ReviewCompanyDetails>}
     * @memberof SeasonReviewResponse
     */
    company?: Array<ReviewCompanyDetails>;
    /**
     * 
     * @type {Date}
     * @memberof SeasonReviewResponse
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof SeasonReviewResponse
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof SeasonReviewResponse
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof SeasonReviewResponse
     */
    reviewId: string;
    /**
     * 
     * @type {Season}
     * @memberof SeasonReviewResponse
     */
    season: Season;
    /**
     * 
     * @type {string}
     * @memberof SeasonReviewResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof SeasonReviewResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof SeasonReviewResponse
     */
    venue?: string;
}

/**
 * Check if a given object implements the SeasonReviewResponse interface.
 */
export function instanceOfSeasonReviewResponse(value: object): value is SeasonReviewResponse {
    if (!('reviewId' in value) || value['reviewId'] === undefined) return false;
    if (!('season' in value) || value['season'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function SeasonReviewResponseFromJSON(json: any): SeasonReviewResponse {
    return SeasonReviewResponseFromJSONTyped(json, false);
}

export function SeasonReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'company': json['company'] == null ? undefined : ((json['company'] as Array<any>).map(ReviewCompanyDetailsFromJSON)),
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'description': json['description'] == null ? undefined : json['description'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'reviewId': json['reviewId'],
        'season': SeasonFromJSON(json['season']),
        'title': json['title'] == null ? undefined : json['title'],
        'userId': json['userId'],
        'venue': json['venue'] == null ? undefined : json['venue'],
    };
}

export function SeasonReviewResponseToJSON(json: any): SeasonReviewResponse {
    return SeasonReviewResponseToJSONTyped(json, false);
}

export function SeasonReviewResponseToJSONTyped(value?: SeasonReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'] == null ? undefined : ((value['company'] as Array<any>).map(ReviewCompanyDetailsToJSON)),
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'description': value['description'],
        'rating': value['rating'],
        'reviewId': value['reviewId'],
        'season': SeasonToJSON(value['season']),
        'title': value['title'],
        'userId': value['userId'],
        'venue': value['venue'],
    };
}

