/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Secret
 */
export interface Secret {
    /**
     * 
     * @type {string}
     * @memberof Secret
     */
    secret: string;
}

/**
 * Check if a given object implements the Secret interface.
 */
export function instanceOfSecret(value: object): value is Secret {
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function SecretFromJSON(json: any): Secret {
    return SecretFromJSONTyped(json, false);
}

export function SecretFromJSONTyped(json: any, ignoreDiscriminator: boolean): Secret {
    if (json == null) {
        return json;
    }
    return {
        
        'secret': json['secret'],
    };
}

export function SecretToJSON(json: any): Secret {
    return SecretToJSONTyped(json, false);
}

export function SecretToJSONTyped(value?: Secret | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secret': value['secret'],
    };
}

