/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShowCredits } from './ShowCredits';
import {
    ShowCreditsFromJSON,
    ShowCreditsFromJSONTyped,
    ShowCreditsToJSON,
    ShowCreditsToJSONTyped,
} from './ShowCredits';
import type { ExternalIds } from './ExternalIds';
import {
    ExternalIdsFromJSON,
    ExternalIdsFromJSONTyped,
    ExternalIdsToJSON,
    ExternalIdsToJSONTyped,
} from './ExternalIds';
import type { Season } from './Season';
import {
    SeasonFromJSON,
    SeasonFromJSONTyped,
    SeasonToJSON,
    SeasonToJSONTyped,
} from './Season';

/**
 * 
 * @export
 * @interface Show
 */
export interface Show {
    /**
     * 
     * @type {string}
     * @memberof Show
     */
    backdropPath?: string;
    /**
     * 
     * @type {ShowCredits}
     * @memberof Show
     */
    credits?: ShowCredits;
    /**
     * 
     * @type {ExternalIds}
     * @memberof Show
     */
    externalIds?: ExternalIds;
    /**
     * 
     * @type {Date}
     * @memberof Show
     */
    firstAirDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Show
     */
    lastAirDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Show
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Show
     */
    nextAirDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof Show
     */
    overview?: string;
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    popularity?: number;
    /**
     * 
     * @type {string}
     * @memberof Show
     */
    posterPath?: string;
    /**
     * 
     * @type {Array<Season>}
     * @memberof Show
     */
    seasons?: Array<Season>;
    /**
     * 
     * @type {string}
     * @memberof Show
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof Show
     */
    tagline?: string;
}

/**
 * Check if a given object implements the Show interface.
 */
export function instanceOfShow(value: object): value is Show {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ShowFromJSON(json: any): Show {
    return ShowFromJSONTyped(json, false);
}

export function ShowFromJSONTyped(json: any, ignoreDiscriminator: boolean): Show {
    if (json == null) {
        return json;
    }
    return {
        
        'backdropPath': json['backdropPath'] == null ? undefined : json['backdropPath'],
        'credits': json['credits'] == null ? undefined : ShowCreditsFromJSON(json['credits']),
        'externalIds': json['externalIds'] == null ? undefined : ExternalIdsFromJSON(json['externalIds']),
        'firstAirDate': json['firstAirDate'] == null ? undefined : (new Date(json['firstAirDate'])),
        'id': json['id'],
        'lastAirDate': json['lastAirDate'] == null ? undefined : (new Date(json['lastAirDate'])),
        'name': json['name'],
        'nextAirDate': json['nextAirDate'] == null ? undefined : (new Date(json['nextAirDate'])),
        'overview': json['overview'] == null ? undefined : json['overview'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'posterPath': json['posterPath'] == null ? undefined : json['posterPath'],
        'seasons': json['seasons'] == null ? undefined : ((json['seasons'] as Array<any>).map(SeasonFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
        'tagline': json['tagline'] == null ? undefined : json['tagline'],
    };
}

export function ShowToJSON(json: any): Show {
    return ShowToJSONTyped(json, false);
}

export function ShowToJSONTyped(value?: Show | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'backdropPath': value['backdropPath'],
        'credits': ShowCreditsToJSON(value['credits']),
        'externalIds': ExternalIdsToJSON(value['externalIds']),
        'firstAirDate': value['firstAirDate'] == null ? undefined : ((value['firstAirDate']).toISOString().substring(0,10)),
        'id': value['id'],
        'lastAirDate': value['lastAirDate'] == null ? undefined : ((value['lastAirDate']).toISOString().substring(0,10)),
        'name': value['name'],
        'nextAirDate': value['nextAirDate'] == null ? undefined : ((value['nextAirDate']).toISOString().substring(0,10)),
        'overview': value['overview'],
        'popularity': value['popularity'],
        'posterPath': value['posterPath'],
        'seasons': value['seasons'] == null ? undefined : ((value['seasons'] as Array<any>).map(SeasonToJSON)),
        'status': value['status'],
        'tagline': value['tagline'],
    };
}

