/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
    RoleToJSONTyped,
} from './Role';

/**
 * 
 * @export
 * @interface ShowCast
 */
export interface ShowCast {
    /**
     * 
     * @type {number}
     * @memberof ShowCast
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ShowCast
     */
    knownForDepartment?: string;
    /**
     * 
     * @type {string}
     * @memberof ShowCast
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ShowCast
     */
    popularity: number;
    /**
     * 
     * @type {string}
     * @memberof ShowCast
     */
    profilePath?: string;
    /**
     * 
     * @type {Array<Role>}
     * @memberof ShowCast
     */
    roles: Array<Role>;
    /**
     * 
     * @type {number}
     * @memberof ShowCast
     */
    totalEpisodeCount: number;
}

/**
 * Check if a given object implements the ShowCast interface.
 */
export function instanceOfShowCast(value: object): value is ShowCast {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('popularity' in value) || value['popularity'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('totalEpisodeCount' in value) || value['totalEpisodeCount'] === undefined) return false;
    return true;
}

export function ShowCastFromJSON(json: any): ShowCast {
    return ShowCastFromJSONTyped(json, false);
}

export function ShowCastFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowCast {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'knownForDepartment': json['knownForDepartment'] == null ? undefined : json['knownForDepartment'],
        'name': json['name'] == null ? undefined : json['name'],
        'popularity': json['popularity'],
        'profilePath': json['profilePath'] == null ? undefined : json['profilePath'],
        'roles': ((json['roles'] as Array<any>).map(RoleFromJSON)),
        'totalEpisodeCount': json['totalEpisodeCount'],
    };
}

export function ShowCastToJSON(json: any): ShowCast {
    return ShowCastToJSONTyped(json, false);
}

export function ShowCastToJSONTyped(value?: ShowCast | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'knownForDepartment': value['knownForDepartment'],
        'name': value['name'],
        'popularity': value['popularity'],
        'profilePath': value['profilePath'],
        'roles': ((value['roles'] as Array<any>).map(RoleToJSON)),
        'totalEpisodeCount': value['totalEpisodeCount'],
    };
}

