/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShowCast } from './ShowCast';
import {
    ShowCastFromJSON,
    ShowCastFromJSONTyped,
    ShowCastToJSON,
    ShowCastToJSONTyped,
} from './ShowCast';
import type { ShowCrew } from './ShowCrew';
import {
    ShowCrewFromJSON,
    ShowCrewFromJSONTyped,
    ShowCrewToJSON,
    ShowCrewToJSONTyped,
} from './ShowCrew';

/**
 * 
 * @export
 * @interface ShowCredits
 */
export interface ShowCredits {
    /**
     * 
     * @type {Array<ShowCast>}
     * @memberof ShowCredits
     */
    cast: Array<ShowCast>;
    /**
     * 
     * @type {Array<ShowCrew>}
     * @memberof ShowCredits
     */
    crew: Array<ShowCrew>;
}

/**
 * Check if a given object implements the ShowCredits interface.
 */
export function instanceOfShowCredits(value: object): value is ShowCredits {
    if (!('cast' in value) || value['cast'] === undefined) return false;
    if (!('crew' in value) || value['crew'] === undefined) return false;
    return true;
}

export function ShowCreditsFromJSON(json: any): ShowCredits {
    return ShowCreditsFromJSONTyped(json, false);
}

export function ShowCreditsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowCredits {
    if (json == null) {
        return json;
    }
    return {
        
        'cast': ((json['cast'] as Array<any>).map(ShowCastFromJSON)),
        'crew': ((json['crew'] as Array<any>).map(ShowCrewFromJSON)),
    };
}

export function ShowCreditsToJSON(json: any): ShowCredits {
    return ShowCreditsToJSONTyped(json, false);
}

export function ShowCreditsToJSONTyped(value?: ShowCredits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cast': ((value['cast'] as Array<any>).map(ShowCastToJSON)),
        'crew': ((value['crew'] as Array<any>).map(ShowCrewToJSON)),
    };
}

