/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShowEntry
 */
export interface ShowEntry {
    /**
     * 
     * @type {string}
     * @memberof ShowEntry
     */
    collectionId: string;
    /**
     * 
     * @type {Date}
     * @memberof ShowEntry
     */
    firstAirDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ShowEntry
     */
    imdbId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ShowEntry
     */
    lastAirDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ShowEntry
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof ShowEntry
     */
    nextAirDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ShowEntry
     */
    posterPath?: string;
    /**
     * 
     * @type {number}
     * @memberof ShowEntry
     */
    showId: number;
    /**
     * 
     * @type {string}
     * @memberof ShowEntry
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof ShowEntry
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ShowEntry
     */
    userId: string;
}

/**
 * Check if a given object implements the ShowEntry interface.
 */
export function instanceOfShowEntry(value: object): value is ShowEntry {
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('showId' in value) || value['showId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ShowEntryFromJSON(json: any): ShowEntry {
    return ShowEntryFromJSONTyped(json, false);
}

export function ShowEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionId': json['collectionId'],
        'firstAirDate': json['firstAirDate'] == null ? undefined : (new Date(json['firstAirDate'])),
        'imdbId': json['imdbId'] == null ? undefined : json['imdbId'],
        'lastAirDate': json['lastAirDate'] == null ? undefined : (new Date(json['lastAirDate'])),
        'name': json['name'],
        'nextAirDate': json['nextAirDate'] == null ? undefined : (new Date(json['nextAirDate'])),
        'posterPath': json['posterPath'] == null ? undefined : json['posterPath'],
        'showId': json['showId'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': (new Date(json['updatedAt'])),
        'userId': json['userId'],
    };
}

export function ShowEntryToJSON(json: any): ShowEntry {
    return ShowEntryToJSONTyped(json, false);
}

export function ShowEntryToJSONTyped(value?: ShowEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collectionId': value['collectionId'],
        'firstAirDate': value['firstAirDate'] == null ? undefined : ((value['firstAirDate']).toISOString().substring(0,10)),
        'imdbId': value['imdbId'],
        'lastAirDate': value['lastAirDate'] == null ? undefined : ((value['lastAirDate']).toISOString().substring(0,10)),
        'name': value['name'],
        'nextAirDate': value['nextAirDate'] == null ? undefined : ((value['nextAirDate']).toISOString().substring(0,10)),
        'posterPath': value['posterPath'],
        'showId': value['showId'],
        'status': value['status'],
        'updatedAt': ((value['updatedAt']).toISOString().substring(0,10)),
        'userId': value['userId'],
    };
}

