/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShowEntry } from './ShowEntry';
import {
    ShowEntryFromJSON,
    ShowEntryFromJSONTyped,
    ShowEntryToJSON,
    ShowEntryToJSONTyped,
} from './ShowEntry';

/**
 * 
 * @export
 * @interface ShowCollection
 */
export interface ShowCollection {
    /**
     * 
     * @type {string}
     * @memberof ShowCollection
     */
    collectionId: string;
    /**
     * 
     * @type {Array<ShowEntry>}
     * @memberof ShowCollection
     */
    entries?: Array<ShowEntry>;
    /**
     * 
     * @type {string}
     * @memberof ShowCollection
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ShowCollection
     */
    userId: string;
}

/**
 * Check if a given object implements the ShowCollection interface.
 */
export function instanceOfShowCollection(value: object): value is ShowCollection {
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ShowCollectionFromJSON(json: any): ShowCollection {
    return ShowCollectionFromJSONTyped(json, false);
}

export function ShowCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionId': json['collectionId'],
        'entries': json['entries'] == null ? undefined : ((json['entries'] as Array<any>).map(ShowEntryFromJSON)),
        'name': json['name'],
        'userId': json['userId'],
    };
}

export function ShowCollectionToJSON(json: any): ShowCollection {
    return ShowCollectionToJSONTyped(json, false);
}

export function ShowCollectionToJSONTyped(value?: ShowCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collectionId': value['collectionId'],
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(ShowEntryToJSON)),
        'name': value['name'],
        'userId': value['userId'],
    };
}

