/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatedCollection
 */
export interface UpdatedCollection {
    /**
     * 
     * @type {string}
     * @memberof UpdatedCollection
     */
    name: string;
}

/**
 * Check if a given object implements the UpdatedCollection interface.
 */
export function instanceOfUpdatedCollection(value: object): value is UpdatedCollection {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdatedCollectionFromJSON(json: any): UpdatedCollection {
    return UpdatedCollectionFromJSONTyped(json, false);
}

export function UpdatedCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatedCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdatedCollectionToJSON(json: any): UpdatedCollection {
    return UpdatedCollectionToJSONTyped(json, false);
}

export function UpdatedCollectionToJSONTyped(value?: UpdatedCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

