/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatedUser
 */
export interface UpdatedUser {
    /**
     * 
     * @type {any}
     * @memberof UpdatedUser
     */
    configuration?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdatedUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatedUser
     */
    lastName?: string;
}

/**
 * Check if a given object implements the UpdatedUser interface.
 */
export function instanceOfUpdatedUser(value: object): value is UpdatedUser {
    return true;
}

export function UpdatedUserFromJSON(json: any): UpdatedUser {
    return UpdatedUserFromJSONTyped(json, false);
}

export function UpdatedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatedUser {
    if (json == null) {
        return json;
    }
    return {
        
        'configuration': json['configuration'] == null ? undefined : json['configuration'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
    };
}

export function UpdatedUserToJSON(json: any): UpdatedUser {
    return UpdatedUserToJSONTyped(json, false);
}

export function UpdatedUserToJSONTyped(value?: UpdatedUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configuration': value['configuration'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

