/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { UserFindResponse } from './UserFindResponse';
import {
    instanceOfUserFindResponse,
    UserFindResponseFromJSON,
    UserFindResponseFromJSONTyped,
    UserFindResponseToJSON,
} from './UserFindResponse';
import type { UserResponse } from './UserResponse';
import {
    instanceOfUserResponse,
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
} from './UserResponse';

/**
 * @type UserRead
 * 
 * @export
 */
export type UserRead = UserFindResponse | UserResponse;

export function UserReadFromJSON(json: any): UserRead {
    return UserReadFromJSONTyped(json, false);
}

export function UserReadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRead {
    if (json == null) {
        return json;
    }
    if (instanceOfUserFindResponse(json)) {
        return UserFindResponseFromJSONTyped(json, true);
    }
    if (instanceOfUserResponse(json)) {
        return UserResponseFromJSONTyped(json, true);
    }

    return {} as any;
}

export function UserReadToJSON(json: any): any {
    return UserReadToJSONTyped(json, false);
}

export function UserReadToJSONTyped(value?: UserRead | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfUserFindResponse(value)) {
        return UserFindResponseToJSON(value as UserFindResponse);
    }
    if (instanceOfUserResponse(value)) {
        return UserResponseToJSON(value as UserResponse);
    }

    return {};
}

