/* tslint:disable */
/* eslint-disable */
/**
 * Framerate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserFindResponse
 */
export interface UserFindResponse {
    /**
     * 
     * @type {string}
     * @memberof UserFindResponse
     */
    avatarUri?: string;
    /**
     * 
     * @type {any}
     * @memberof UserFindResponse
     */
    configuration: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserFindResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserFindResponse
     */
    firstName: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserFindResponse
     */
    isAdmin: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserFindResponse
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof UserFindResponse
     */
    userId: string;
}

/**
 * Check if a given object implements the UserFindResponse interface.
 */
export function instanceOfUserFindResponse(value: object): value is UserFindResponse {
    if (!('configuration' in value) || value['configuration'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('isAdmin' in value) || value['isAdmin'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserFindResponseFromJSON(json: any): UserFindResponse {
    return UserFindResponseFromJSONTyped(json, false);
}

export function UserFindResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFindResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarUri': json['avatarUri'] == null ? undefined : json['avatarUri'],
        'configuration': json['configuration'],
        'email': json['email'],
        'firstName': json['firstName'],
        'isAdmin': json['isAdmin'],
        'lastName': json['lastName'],
        'userId': json['userId'],
    };
}

export function UserFindResponseToJSON(json: any): UserFindResponse {
    return UserFindResponseToJSONTyped(json, false);
}

export function UserFindResponseToJSONTyped(value?: UserFindResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatarUri': value['avatarUri'],
        'configuration': value['configuration'],
        'email': value['email'],
        'firstName': value['firstName'],
        'isAdmin': value['isAdmin'],
        'lastName': value['lastName'],
        'userId': value['userId'],
    };
}

